### ISSUE TITLE
default template cannot be found

### ISSUE THREAD

**Issue by svandragt** [lektor/lektor-tags#5]
It's not clear from the setting up instructions that a `/templates/tags.html` template is required. The readme says that the plugin ships with a default template. I've not checked this, but it definatelly does not get called correctly:

ValueError: The given value (u'~/Library/Caches/Lektor/packages/c2c6742dbf0a90d60bcba133cf9f3d16/templates/tags.html') is not below the source folder (u~/Dropbox/Lektor/vandragt.com')

**Comment by philnelson** [comment]
Creating lektor_tags_default_template.html under `templates` fixed this for me.

**Comment by svandragt** [comment]
Cheers Phil how did you figure that out?

**Comment by dairiki** [comment]
I think the issue is that shipping [_package data_](https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data) in a Python distribution requires that the data files live within a _package_'s directory.  As things stand, we do not have a package in which to include any package data: `lektor_tags` is a _module_ (its source code is in a top-level file named `lektor_tags.py`), rather than a _package_ (in which its code would be in `lektor_tags/__init__.py`).

(Currently, at least, it appears as if the default template is not included in the wheel at all.)
